// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// enumerate_string_sequence
Rcpp::IntegerVector enumerate_string_sequence(Rcpp::Nullable<Rcpp::StringVector> sequence, Rcpp::Nullable<Rcpp::StringVector> alphabet);
RcppExport SEXP _seqR_enumerate_string_sequence(SEXP sequenceSEXP, SEXP alphabetSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::StringVector> >::type sequence(sequenceSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::StringVector> >::type alphabet(alphabetSEXP);
    rcpp_result_gen = Rcpp::wrap(enumerate_string_sequence(sequence, alphabet));
    return rcpp_result_gen;
END_RCPP
}
// enumerate_integer_sequence
Rcpp::IntegerVector enumerate_integer_sequence(Rcpp::Nullable<Rcpp::IntegerVector> sequence, Rcpp::Nullable<Rcpp::IntegerVector> alphabet);
RcppExport SEXP _seqR_enumerate_integer_sequence(SEXP sequenceSEXP, SEXP alphabetSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::IntegerVector> >::type sequence(sequenceSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::IntegerVector> >::type alphabet(alphabetSEXP);
    rcpp_result_gen = Rcpp::wrap(enumerate_integer_sequence(sequence, alphabet));
    return rcpp_result_gen;
END_RCPP
}
// enumerate_numeric_sequence
Rcpp::IntegerVector enumerate_numeric_sequence(Rcpp::Nullable<Rcpp::NumericVector> sequence, Rcpp::Nullable<Rcpp::NumericVector> alphabet);
RcppExport SEXP _seqR_enumerate_numeric_sequence(SEXP sequenceSEXP, SEXP alphabetSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::NumericVector> >::type sequence(sequenceSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::NumericVector> >::type alphabet(alphabetSEXP);
    rcpp_result_gen = Rcpp::wrap(enumerate_numeric_sequence(sequence, alphabet));
    return rcpp_result_gen;
END_RCPP
}
// get_not_allowed_sequence_positions
Rcpp::IntegerVector get_not_allowed_sequence_positions(Rcpp::IntegerVector encoded_sequence);
RcppExport SEXP _seqR_get_not_allowed_sequence_positions(SEXP encoded_sequenceSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type encoded_sequence(encoded_sequenceSEXP);
    rcpp_result_gen = Rcpp::wrap(get_not_allowed_sequence_positions(encoded_sequence));
    return rcpp_result_gen;
END_RCPP
}
// compute_power_fast
int compute_power_fast(int base, int power, int modulo);
RcppExport SEXP _seqR_compute_power_fast(SEXP baseSEXP, SEXP powerSEXP, SEXP moduloSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type base(baseSEXP);
    Rcpp::traits::input_parameter< int >::type power(powerSEXP);
    Rcpp::traits::input_parameter< int >::type modulo(moduloSEXP);
    rcpp_result_gen = Rcpp::wrap(compute_power_fast(base, power, modulo));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_seqR_enumerate_string_sequence", (DL_FUNC) &_seqR_enumerate_string_sequence, 2},
    {"_seqR_enumerate_integer_sequence", (DL_FUNC) &_seqR_enumerate_integer_sequence, 2},
    {"_seqR_enumerate_numeric_sequence", (DL_FUNC) &_seqR_enumerate_numeric_sequence, 2},
    {"_seqR_get_not_allowed_sequence_positions", (DL_FUNC) &_seqR_get_not_allowed_sequence_positions, 1},
    {"_seqR_compute_power_fast", (DL_FUNC) &_seqR_compute_power_fast, 3},
    {NULL, NULL, 0}
};

RcppExport void R_init_seqR(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
