# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @export
enumerate_string_sequence <- function(sequence, alphabet) {
    .Call('_seqR_enumerate_string_sequence', PACKAGE = 'seqR', sequence, alphabet)
}

#' @export
enumerate_integer_sequence <- function(sequence, alphabet) {
    .Call('_seqR_enumerate_integer_sequence', PACKAGE = 'seqR', sequence, alphabet)
}

#' @export
enumerate_numeric_sequence <- function(sequence, alphabet) {
    .Call('_seqR_enumerate_numeric_sequence', PACKAGE = 'seqR', sequence, alphabet)
}

#' @export
get_not_allowed_sequence_positions <- function(encoded_sequence) {
    .Call('_seqR_get_not_allowed_sequence_positions', PACKAGE = 'seqR', encoded_sequence)
}

#' @export
count_kmers_hashed <- function(encoded_sequence, k, positional_kmer, P, P_K_1, M) {
    .Call('_seqR_count_kmers_hashed', PACKAGE = 'seqR', encoded_sequence, k, positional_kmer, P, P_K_1, M)
}

#' @export
decode_kmer <- function(encoded_sequence, d, begin_position, decoder, positional_kmer) {
    .Call('_seqR_decode_kmer', PACKAGE = 'seqR', encoded_sequence, d, begin_position, decoder, positional_kmer)
}

#' @export
generate_all_kmers <- function(k, P, M, decoder) {
    .Call('_seqR_generate_all_kmers', PACKAGE = 'seqR', k, P, M, decoder)
}

